extends:
  - spectral:oas

rules:
  # Строгие правила, совместимые с Spectral v6
  operation-operationId-unique: true
  no-$ref-siblings: error
  operation-success-response: error
  # Предупреждения для полезных, но не критичных моментов
  oas3-api-servers: warn
  info-description: warn
  operation-tags: warn
